build:
  binary: rocket-lang
  main: main.go
  ldflags:
    - >
      -s -w
      -X github.com/flipez/rocket-lang/repl.buildVersion={{.Version}}
      -X github.com/flipez/rocket-lang/repl.buildDate={{.Date}}
  goos:
    - linux
    - darwin
    - freebsd
    - windows
  goarch:
    - amd64
    - arm
    - arm64
  env:
    - CGO_ENABLED=0

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"

release:
  draft: true

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "checksums.txt"

nfpms:
  - vendor: Flipez
    homepage: https://rocket-lang.org
    maintainer: Flipez <code@brauser.io>
    description: Implementation of the monkey lang
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    id: packages
    file_name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}_{{ .Tag }}"

# .goreleaser.yml
brews:
  -
    name: rocket-lang
    tap:
      owner: flipez
      name: homebrew-tap

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Flipez
      email: code@brauser.io

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    folder: Formula

    homepage: "https://auch.cool/"
    license: "MIT"

publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .secrets.FURY_TOKEN }}@push.fury.io/flipez/